### ISSUE TITLE
Querying same relationship with different params.

### ISSUE THREAD

**Issue by altrim** [mdehoog/ember-data-has-many-query#1]
Hello,

I have a service with 2 computed properties where I query the same relation with different params but the request is made only once and both properties have the same data. 

E.g in the service I have 

    firstProperty: Ember.computed({
     get() {
        return model.query('role', {name: 'admin'});
     }
    }),

    secondProperty: Ember.computed({
     get() {
        return model.query('role', {name: 'moderator'});
     }
    }),

But in the template when iterating I have in both properties the same data (from firstProperty). 
Looks like the second request never runs. 

Is this intended? Is there a way to avoid this?

**Comment by mdehoog** [comment]
Only one hasMany query can be active/stored at one time per relationship. This is because the results are stored in the hasMany attribute itself, so running another query will override them. Also, multiple queries cannot run concurrently, because the adapter will attach the second query to the first query's promise.

One way to get around this is to only run one query at a time, and store the results in a separate property. For your example, something like this:
```
init: function () {
  this._super(...arguments);
  var self = this;
  model.query('role', {name: 'admin'}).then(function(adminResponse) {
    var admin = Ember.A();
    admin.push.apply(admin, adminResponse);
    self.set('firstProperty', admin);
    model.query('role', {name: 'moderator'}).then(function(moderatorResponse) {
      var moderator = Ember.A();
      moderator.push.apply(moderator, moderatorResponse);
      self.set('secondProperty', moderator);
    });
  });
},
firstProperty: Ember.A(),
secondProperty: Ember.A()
```
Note that doing a `model.get('role')` will return whatever was last queried.

**Comment by altrim** [comment]
Thanks for the clarifications, will try to use the workaround by running one query at a time.
