### ISSUE TITLE
Add Template Helper

### ISSUE THREAD

**Issue by jackmatt2** [mdehoog/ember-data-has-many-query#12]
Would be nice if there was a template helper for this also.

    {{has-many-query model 'comments' query=(hash title='hello world')}}

**Comment by mdehoog** [comment]
This could be slightly confusing as it would appear you could make multiple queries in the same template with different query parameters. This addon only supports a single query at a time, due to the fact that the results are stored in the model's `hasMany` array. IMHO it makes more sense to limit querying in the route's `model` function due to this limitation.

**Comment by jackmatt2** [comment]
OK, this makes sense then.
